FROM --platform=linux/amd64 python:3.9-slim
ENV TZ="America/Chicago"
WORKDIR /Shadow_Application
COPY requirements.txt /Shadow_Application/
RUN pip install --trusted-host pypi.python.org -r requirements.txt
COPY . /Shadow_Application
ENV FLASK_ENV=production
EXPOSE 4000
CMD ["python", "ShadowAnalysisServer.py"]
